### ISSUE TITLE
Logo/icon Proposal for FastSave-Android

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [yehiahd/FastSave-Android#2]
Hello,
This my logo/Icon design for your project. It's free for your project.

I design this logo using adobe illustrator cc 2018. I hope you like this logo.

![fastsave-android-01](https://user-images.githubusercontent.com/35112507/39232011-c19ab330-488d-11e8-858b-cb47c08f5317.jpg)

If you need anything change please contact me

Md Nazmul Hasan
Email : nazmul.hasan27771@gmail.com

Thank You.

**Comment by yehiahd** [comment]
@mdnazmulhasan27771 
Thank you for your effort. I really like your design and your creativity. :smiley: 
So well done.
Thanks again.
