### ISSUE TITLE
Program type already present: com.google.common.annotations.Beta Message{kind=ERROR, text=Program type already present: com.google.common.annotations.Beta, sources=[Unknown source file], tool name=Optional.of(D8)}

### ISSUE THREAD

**Issue by 4w415m** [yehiahd/FastSave-Android#3]
When I include the dependency for your library in my project it gives the above error. If you want to see my whole build.gradle file, please let me know.

**Comment by yehiahd** [comment]
Thanks for using the library and I have done with some search about your problem and found the solution
Please take a look at this answer on stackoverflow.com so we can solve this problem. So please try it out and let me know if it solved or still need help 😁
https://stackoverflow.com/a/50520218/5335885
Best of luck 😁

**Comment by 4w415m** [comment]
Hey Mohamed, thanks for your response. It did solve my problem. I found the
exact same solution yesterday but didn't even try it.

**Comment by yehiahd** [comment]
You are welcome 😄
Happy coding 👌
