### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [yehiahd/FastSave-Android#4]
Hi @yehiahd . I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.
Best Regard

**Comment by yehiahd** [comment]
Hi @mirzazulfan Thank you so much for your propose but this project is a libraries that used by developer so i think the logo for this project is not a big deal.
Once again thank you :smile:

**Comment by mirzazulfan** [comment]
Its ok. Thank you. Have a nice day.
