### ISSUE TITLE
Crash on getObjectList on several device like xiaomi

### ISSUE THREAD

**Issue by dodyy** [yehiahd/FastSave-Android#5]
Fatal Exception: java.lang.AssertionError
illegal type variable reference

libcore.reflect.TypeVariableImpl.resolve (TypeVariableImpl.java:111)
com.google.common.reflect.TypeToken.where (TypeToken.java:253)

is there still a bug?

**Comment by yehiahd** [comment]
Actually My device is xiaomi already and everything works good but for your case I've updated the inner dependencies of the library and i hope your issue to be solved. otherwise, if you still facing the same issue, let me know again so i will revisit it technically.
Best.
